version: '3.9'
services:
  app:
    container_name: ${APP_CONTAINER}
    image: ${APP_CONTAINER}:${GO_VERSION}-${ALPINE_VERSION}
    build:
      context: ../.
      dockerfile: ./deployments/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_BIN: ${APP_BIN}
        GO_VERSION: ${GO_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        WORKDIR: ${WORKDIR}
        PORT: ${PORT}
    restart: on-failure
    env_file: 
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - 8080:${PORT}
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}
    depends_on:
      - pgdb

  pgdb:
    # TODO: implement persistance data(volumen) for PG_DATA
    container_name: ${PGDB_CONTAINER}
    image: postgres:alpine${ALPINE_VERSION}
    restart: on-failure
    environment:
      POSTGRES_DB: ${DATABASE_POSTGRES_DBNAME}
      POSTGRES_USER: ${DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWD}
    ports:
      - ${DATABASE_POSTGRES_PORT}:5432
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}

  pgadmin:
    container_name: ${PGADMIN_CONTAINER}
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}
    depends_on:
      - pgdb


networks:
  # TODO: dynamically set network name with the prefix APP_NAME 
  camgo-net:
    external: true