version: '3.9'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    image: ${APP_IMAGE}
    build:
      context: ../.
      dockerfile: ./deployments/Dockerfile
      args:
        GO_VERSION: ${GO_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        APP_NAME: ${APP_NAME}
        APP_PORT: ${APP_PORT}
        APP_WORKDIR: ${APP_WORKDIR}
        DB_MIGRATIONS_DIR: ${DATABASE_MIGRATIONS_DIR}
    restart: on-failure
    environment:
      APPLICATION_NAME: ${APP_NAME}
      APPLICATION_VERSION: ${APP_VERSION}
      HTTP_SERVER_HOST: ${APP_HOST}
      HTTP_SERVER_PORT: ${APP_PORT}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_POSTGRES_HOST: ${PGDB_CONTAINER_NAME}
      DATABASE_POSTGRES_PORT: ${PGDB_PORT}
      DATABASE_POSTGRES_USER: ${PGDB_USER}
      DATABASE_POSTGRES_PASSWD: ${PGDB_PASSWD}
      DATABASE_POSTGRES_DBNAME: ${PGDB_DBNAME}
    ports:
      - 80:${APP_PORT}
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}
    depends_on:
      - pgdb

  pgdb:
    # TODO: implement persistance data(volumen) for PG_DATA
    container_name: ${PGDB_CONTAINER_NAME}
    image: ${PGDB_IMAGE}
    restart: on-failure
    environment:
      POSTGRES_DB: ${PGDB_DBNAME}
      POSTGRES_USER: ${PGDB_USER}
      POSTGRES_PASSWORD: ${PGDB_PASSWD}
    ports:
      - ${PGDB_PORT}:5432
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${PGADMIN_IMAGE}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      # TODO: dynamically set network name with the prefix APP_NAME 
      camgo-net: {}
    depends_on:
      - pgdb


networks:
  # TODO: dynamically set network name with the prefix APP_NAME 
  camgo-net:
    external: true